[versions]
dokkaGradlePluginVersion = "2.2.0"
githubApiVersion = "1.330"
gradle = "9.4.0"
kotlin = "2.4.10"
gradleVersion = "9.4.0"
compileSdk = "37"
targetSdk = "37"
minSdk = "23"
jvmVersion = "11"

dokkaVersion = "2.2.0"
appcompatVersion = "1.8.0"
espressoVersion = "3.7.0"

junitVersion = "4.13.2"
junitExtVersion = "1.3.0"
testRunnerVersion = "1.7.0"
kotlinGradlePluginVersion = "2.4.10"
multidexVersion = "2.0.1"
materialVersion = "1.14.0"
activityComposeVersion = "1.13.0"

composeVersion = "1.12.0"
composeMultiplatform = "1.12.0"
materialsIcon = "1.7.8"

[libraries]
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaGradlePluginVersion" }
github-api = { module = "org.kohsuke:github-api", version.ref = "githubApiVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }

com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }

androidx-test-espresso-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoVersion" }

androidx-compose-ui-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeVersion" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeVersion" }
androidx-compose-material-iconsCore = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "materialsIcon"  }

androidx-compose-ui-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeVersion"  }
androidx-compose-ui-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeVersion"  }

gradle-v851 = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExtVersion" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunnerVersion" }

androidx-multidex-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidexVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }
org-jetbrains-dokka-kotlinAsJavaPlugin = { group = "org.jetbrains.dokka", name = "kotlin-as-java-plugin", version.ref = "dokkaVersion" }

jetbrains-compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "composeMultiplatform" }
jetbrains-compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "composeMultiplatform" }
jetbrains-compose-material = { group = "org.jetbrains.compose.material", name = "material", version.ref = "composeMultiplatform" }
jetbrains-compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "composeMultiplatform" }
jetbrains-compose-ui-test = { group = "org.jetbrains.compose.ui", name = "ui-test", version.ref = "composeMultiplatform" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }