name: Master

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle
      - name: dokkaHtml
        run: |
          ./gradlew clean dokkaHtml
      - name: Build Page
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./html"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

  deploy-ossrh:
    name: Deploy to OSSRH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: Deploy to OSSRH
        run: ./gradlew :compose:publishDefaultPublicationToOSSHRRepository -PreleaseMode=SNAPSHOT --stacktrace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  deploy-github:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: Deploy to GitHub
        run: ./gradlew :compose:publishDefaultPublicationToGithubRepository -PreleaseMode=SNAPSHOT --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
