name: Publish Release
on:
  release:
    types: [published]
jobs:
  deploy-osshr:
    name: Deploy to OSSHR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: deploy-release
        run: ./gradlew :compose:publishDefaultPublicationToOSSHRRepository -PreleaseMode=RELEASE --stacktrace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  deploy-github:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: gradle
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: Deploy to GitHub
        run: ./gradlew :compose:publishDefaultPublicationToGithubRepository -PreleaseMode=SNAPSHOT --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
