name: Publish Release
on:
  release:
    types: [published]
jobs:
  deploy-osshr:
    name: Deploy to OSSHR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: deploy-release
        run: ./gradlew :compose:publishDefaultPublicationToOSSHRRepository -PreleaseMode=RELEASE --stacktrace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
