name: PR
on:
  pull_request_target:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/master-github-pages.yaml'
      - '.github/workflows/release-deploy.yaml'
jobs:
  assemble-library:
    name: Assemble Compose Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Assemble Compose library
        run: bash ./gradlew compose:assembleDebug
        
  assemble-debug-apk:
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Assemble Debug APK
        run: bash ./gradlew sample:assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: sample/build/outputs/apk/debug/sample-debug.apk

  assemble-debug-android-test-apk:
    name: Assemble Instrumental APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Assemble Instrumental APK
        run: bash ./gradlew sample:assembleDebugAndroidTest
      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk

  firebase-lab-test:
    needs: [ assemble-debug-apk, assemble-debug-android-test-apk ]
    name: Firebase Instrumental API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api: [ 26, 27, 28, 29, 30, 31, 32, 33 ]
    steps:
      - uses: actions/checkout@v3
      - name: Download APKs
        uses: actions/download-artifact@v3
        with:
          name: apk
      - name: Run tests on Firebase Test Lab for API ${{ matrix.api }}
        uses: vacxe/firebase-test-lab-action@0.0.6
        with:
          service-account: ${{ secrets.FIREBASE_TESTLAB_JSON }}
          app: apk/sample-debug.apk
          test: apk/sample-debug-androidTest.apk
          device-id: MediumPhone.arm
          os-version-id: ${{ matrix.api }}
          num-flaky-test-attempts: 4
