name: sample-connected-checks
on: [ pull_request ]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo $GPG_PASSPHRASE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2