name: UI Library Publish Release

on:
  push:
    tags:
      - 'ui_*'

jobs:
  publish-release:
    uses: ./.github/workflows/publish-release-workflow.yaml
    with:
      project: compose-ui
    secrets: inherit
