name: Compose Library Publish Release

on:
  push:
    tags:
      - 'compose_*'

jobs:
  publish-release:
    uses: ./.github/workflows/publish-release-workflow.yaml
    with:
      project: compose
    secrets: inherit
