name: Publish Release

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  deploy-osshr:
    name: Deploy ${{ inputs.project }} to OSSHR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: little-core-labs/get-git-tag@v3.0.2
      - name: Deploy Release to OSSRH
        run: ./gradlew :$PROJECT:publishDefaultPublicationToOSSHRRepository -PreleaseMode=RELEASE
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PROJECT: ${{ inputs.project }}
