name: Pull Request assemble artifacts
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/master-github-pages.yaml'
      - '.github/workflows/release-deploy.yaml'
jobs:
  assemble-debug-apk:
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Assemble Debug APK
        run: bash ./gradlew sample:assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: sample/build/outputs/apk/debug/sample-debug.apk

  assemble-debug-android-test-apk:
    name: Assemble Instrumental APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - name: Assemble Instrumental APK
        run: bash ./gradlew sample:assembleDebugAndroidTest
      - name: Upload app APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: sample/build/outputs/apk/androidTest/debug/sample-debug-androidTest.apk
