name: Pull Request Documentation Checks
on:
  pull_request:
    paths:
      - 'documentation/**'
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    name: Build Documentation

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Install dependencies
        working-directory: ./documentation
        run: npm install

      - name: Build site
        working-directory: ./documentation
        run: npm run build
